[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_port = COM4
monitor_port = COM4
monitor_speed = 115200
upload_speed = 115200

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = huge_app.csv

board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi

build_flags =
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM