[env:esp32s3_n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

upload_port = COM3 # 不同的PC串口可能要改
monitor_port = COM3
monitor_speed = 115200
upload_speed = 916200 # 波特率可以加快一点 9600*n 

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = huge_app.csv

board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi

build_flags =
    -DBOARD_HAS_PSRAM # 环境原因，暂时删除了CDC，如果没有反应可以把这一行加上
    # -DARDUINO_USB_CDC_ON_BOOT=1
